promotoria = ['5ª PmJ Natal', '61ª PmJ Natal', 'PmJ São José de Mipibu', '57ª PmJ Natal', '47ª PmJ Natal',
              '54ª PmJ Natal', '9ª PmJ Parnamirim', '6ª PmJ Parnamirim', '4ª PmJ São Gonçalo do Amarante', 'PmJ Lajes',
              '48ª PmJ Natal', '56ª PmJ Natal', '28ª PmJ Natal', '72ª PmJ Natal', 'PmJ São Paulo do Potengi',
              '46ª PmJ Natal', '67ª PmJ Natal', '1ª PmJ Nova Cruz', '42ª PmJ Natal', 'PmJ Jucurutu', '17ª PmJ Mossoró',
              '26ª PmJ Natal', '8ª PmJ Parnamirim', '3ª PmJ Parnamirim', '59ª PmJ Natal', '2ª PmJ Areia Branca',
              '2ª PmJ Nísia  Floresta', '1ª PmJ Macau', '2ª PmJ Canguaretama', '9ª PmJ Natal', '2ª PmJ Goianinha',
              '80ª PmJ Natal', 'PmJ  São Bento do Norte', 'PmJ Almino Afonso', '3ª PmJ Mossoró', '11ª PmJ Mossoró',
              '16ª PmJ Natal', '2ª PmJ São Gonçalo do Amarante', '1ª PmJ Ceará-Mirim', '2ª PmJ Caicó',
              '1ª PmJ Parnamirim', '1ª PmJ Canguaretama', '19ª PmJ Mossoró', '14ª PmJ Natal', '1ª PmJ Areia Branca',
              'PmJ São José do Campestre', '1ª PmJ Goianinha', '2ª PmJ Macau', '12ª PmJ Parnamirim', '18ª PmJ Mossoró',
              '2ª PmJ Ceará-Mirim', '4ª PmJ Ceará-Mirim', '3ª PmJ Assu', '29ª PmJ Natal', '12ª PmJ Mossoró',
              '22ª PmJ Natal', '27ª PmJ Natal', '15ª PmJ Mossoró', '1ª PmJ Assu', '76ª PmJ Natal',
              '2ª PmJ Currais Novos', '44ª PmJ Natal', 'PmJ Caraúbas', 'PmJ Touros', '33ª PmJ Natal', 'PmJ Umarizal',
              '5ª PmJ Parnamirim', 'PmJ Marcelino Vieira', '65ª PmJ Natal', '2ª PmJ Pau dos Ferros',
              '1ª PmJ Currais Novos', '3ª PmJ São Gonçalo do Amarante', '1ª PmJ Apodi', '13ª PmJ Parnamirim',
              '2ª PmJ Apodi', '1ª PmJ Nísia Floresta', 'PmJ Jardim de Piranhas', '4ª PmJ Parnamirim', '51ª PmJ Natal',
              '5ª PmJ Mossoró', '3ª PmJ Natal', '60ª PmJ Natal', '36ª PmJ Natal', '2ª PmJ Santa Cruz', '2ª PmJ Assu',
              'PmJ São Miguel', 'PmJ Martins', '1ª PmJ Pau dos Ferros', 'PmJ Acari', '3ª PmJ Macaíba', 'PmJ São Tomé',
              'PmJ Angicos', '3ª PmJ Ceará-Mirim', 'PmJ Pendências', '68ª PmJ Natal', '8ª PmJ Mossoró',
              '1ª PmJ Monte Alegre', '24ª PmJ Natal', 'PmJ Santo Antônio', '4ª PmJ Natal', '16ª PmJ Mossoró',
              '18ª PmJ Natal', '11ª PmJ Parnamirim (Dr. Frazão)', 'PmJ Baraúna', '1ª PmJ João Câmara', 'PmJ Ipanguaçu',
              '7ª PmJ Parnamirim', '53ª PmJ Natal', '20ª PmJ Natal', '3ª PmJ Pau dos Ferros', '43ª PmJ Natal',
              '10ª PmJ Mossoró', 'PmJ Portalegre', 'PmJ Patu', '2ª PmJ Macaíba', '13ª PmJ Mossoró', '1ª PmJ Macaíba',
              'PmJ Campo Grande', '1ª PmJ Caicó', 'PmJ Cruzeta', '6ª PmJ Mossoró', '79ª PmJ Natal', '37ª PmJ Natal',
              '13ª PmJ Natal', 'PmJ Parelhas', '9ª PmJ Mossoró', '2ª PmJ João Câmara', '4ª PmJ Macaíba', '1ª PmJ Natal',
              '3ª PmJ Caicó', '75ª PmJ Natal', '49ª PmJ Natal', '25ª PmJ Natal', '2ª PmJ Parnamirim', '81ª PmJ Natal',
              '21ª PmJ Natal', '74ª PmJ Natal', '73ª PmJ Natal', '63ª PmJ Natal', '52ª PmJ Natal', '50ª PmJ Natal',
              '31ª PmJ Natal', '23ª PmJ Natal', '11ª PmJ Natal', '7ª PmJ Natal', '78ª PmJ Natal', '58ª PmJ Natal',
              '4ª PmJ Mossoró', '35ª PmJ Natal', '7ª PmJ Mossoró', '14ª PmJ Mossoró', '69ª PmJ Natal', '15ª PmJ Natal',
              '10ª PmJ Natal', '2ª PmJ Mossoró', '70ª PmJ Natal', '19ª PmJ Natal', '10ª PmJ Parnamirim',
              '71ª PmJ Natal', '45ª PmJ Natal', '62ª PmJ Natal', '1ª PmJ Mossoró', '1ª PmJ São Gonçalo do Amarante',
              '1ª PmJ Santa Cruz', '2ª PmJ Nova Cruz', '2ª PmJ Monte Alegre', '2ª PmJ Extremoz', '1ª PmJ Extremoz',
              'PmJ Tangará', 'PmJ Santana do Matos', 'PmJ Luís Gomes', 'PmJ Jardim do Seridó', 'PmJ Alexandria',
              'PmJ Upanema', 'PmJ Florânia']

promotores = ["Adriana Lira Da Luz Mello",
              "Adriana Medeiros Gurgel De Faria",
              "Adriana Melo Diniz",
              "Adriano Da Gama Dantas",
              "Afonso De Ligório Bezerra Júnior",
              "Alexandre Gonçalves Frazão",
              "Alexandre Matos Pessoa Da Cunha Lima",
              "Alysson Michel De Azevedo Dantas",
              "Ana Araújo Ximenes Teixeira Mendes",
              "Ana Carolina Lucena De Freitas Sideaux",
              "Ana Jovina De Oliveira Ferreira",
              "Ana Márcia Moraes Machado",
              "Ana Patrícia Montenegro De Medeiros Duarte",
              "Andre Mauro Lacerda Azevedo",
              "André Nilton Rodrigues De Oliveira",
              "Andréa Sousa Mariz De Faria",
              "Antônio Carlos Lorenzetti De Mello",
              "Antônio Cláudio Linhares Araújo",
              "Armando Lúcio Ribeiro",
              "Augusto Carlos Rocha De Lima",
              "Augusto Flávio De Araújo Azevedo",
              "Baltazar Patricio Marinho De Figueiredo",
              "Beatriz Azevedo De Oliveira",
              "Benilton De Lima Souza",
              "Carlos Henrique Harper Cox",
              "Carlos Henrique Rodrigues Da Silva",
              "Cátia Tatiana Cortez Hermínio",
              "Christiano Baía Fernandes De Araújo",
              "Cláudio Alexandre De Melo Onofre",
              "Cláudio Roberto Alves Emerenciano",
              "Clayton Barreto De Oliveira",
              "Dalila Rocha De Melo",
              "Daniel Fernandes De Melo Lima",
              "Daniel Lessa De Azevedo Da Aldeia",
              "Daniel Lobo Olímpio",
              "Daniel Robson Linhares De Lima",
              "Danielle De Carvalho Fernandes",
              "Danielli Christine De Oliveira Gomes Pereira",
              "David Costa Benevides",
              "Diogo Augusto Vidal Padre",
              "Diogo Maia Cantídio",
              "Domingos Sávio Brito Bastos Almeida",
              "Edgard Jurema De Medeiros",
              "Edísio Souto Neto",
              "Eduardo Medeiros Cavalcanti",
              "Elaine Cardoso De Matos Novais Teixeira",
              "Eldro Sucupira Feitosa",
              "Emanuel Dhayan Bezerra De Almeida",
              "Emília Matilde Araújo De Vasconcelos Leite Zumba",
              "Érica Verícia Canuto De Oliveira Veras",
              "Erickson Girley Barros Dos Santos",
              "Eudo Rodrigues Leite",
              "Eugênio Carvalho Ribeiro",
              "Fábio De Weimar Thé",
              "Fábio Souza Carvalho Melo",
              "Fausto Faustino De Franca Junior",
              "Fernanda Bezerra Guerreiro Lobo",
              "Fernanda Lacerda De Miranda Arenhart",
              "Fladja Raiane Soares De Souza",
              "Flávia Felício Mathias Da Silva",
              "Flavia Medeiros",
              "Flávia Queiroz Da Silva",
              "Flávio Henrique De Oliveira Nóbrega",
              "Flávio Nunes Da Silva",
              "Flávio Sérgio De Souza Pontes Filho",
              "Francisco Alexandre Amorim Marciano",
              "Francisco Hélio De Morais Júnior",
              "Frederico Augusto Pires Zelaya",
              "Geraldo Rufino De Araújo Júnior",
              "Gerliana Maria Silva Araújo Rocha",
              "Gilcilene Da Costa De Sousa",
              "Gilka Dias Da Mata",
              "Giovanni Rosado Diógenes Paiva",
              "Glaucio Pinto Garcia",
              "Graziela Esteves Viana Hounie",
              "Guglielmo Marconi Soares De Castro",
              "Hellen De Macedo Maciel",
              "Hermínio Souza Perez Júnior",
              "Iara Maria Pinheiro De Albuquerque",
              "Isabel De Siqueira Menezes",
              "Isabela Lúcio Lima Da Silva",
              "Isabelita Garcia Gomes Neto Rosas",
              "Ítalo Moreira Martins",
              "Ivaneide Feitosa Confessor",
              "Ivanildo Alves Da Silveira",
              "Iveluska Alves Xavier Da Costa Lemos",
              "Izabel Cristina Pinheiro",
              "Janayna De Araújo Francisco",
              "Jann Polacek Melo Cardoso",
              "Jeane De Lima Dantas Dos Santos",
              "João Vicente Silva De Vasconcelos Leite",
              "José Alves De Rezende Neto",
              "Jose Augusto De Souza Peres Filho",
              "José Roberto Torres Da Silva Batista",
              "Jovino Pereira Da Costa Sobrinho",
              "Juliana Alcoforado De Lucena",
              "Juliana Limeira Teixeira Xavier",
              "Kalina Correia Filgueira",
              "Kaline Cristina Dantas Pinto De Andrade",
              "Karine De Medeiros Crispim",
              "Kariny Gonçalves Fonseca",
              "Keiviany Silva De Sena",
              "Lara Maia Teixeira Morais",
              "Leila Regina De Brito Andrade",
              "Lenildo Queiroz Bezerra",
              "Leonardo Cartaxo Trigueiro",
              "Leonardo Dantas Nagashima",
              "Lidiane Oliveira Dos Santos Câmara",
              "Liv Ferreira Augusto Severo Queiroz",
              "Luciana Andrade D’assunção",
              "Luciana Maria Maciel Cavalcanti Ferreira De Melo",
              "Luciana Queiroz Lopes De Melo Martins Pessoa",
              "Lúcio Romero Marinho Pereira",
              "Lucy Figueira Peixoto Mariano Da Silva",
              "Luiz Eduardo Marinho Costa",
              "Mac Lennon Lira Dos Santos Leite",
              "Marcella Pereira Da Nobrega",
              "Marcelo Coutinho Meireles",
              "Marcelo De Oliveira Santos",
              "Márcio Cardoso Santos",
              "Marconi Antas Falcone De Melo",
              "Marcos Adair Nunes",
              "Marcus Aurélio De Freitas Barros",
              "Maria Danielle Simões Veras Ribeiro",
              "Maria Zélia Henriques Pimentel De Vasconcelos",
              "Mariana Marinho Barbalho",
              "Mariana Rebello Cunha Melo De Sá",
              "Mariano Paganini Lauria",
              "Marília Regina Soares Cunha Fernandes",
              "Melissa Barbosa Tabosa Do Egito",
              "Micaele Fortes Caddah",
              "Michelle Dantas De Carvalho",
              "Moisés De Araújo Martins",
              "Morton Luiz Faria De Medeiros",
              "Núbia Eliane De Souza Diógenes",
              "Olegário Gurgel Ferreira Gomes",
              "Oscar Hugo De Souza Ramos",
              "Patrícia Albino Galvão Pontes",
              "Patrícia Antunes Martins",
              "Paulo Batista Lopes Neto",
              "Paulo Carvalho Ribeiro",
              "Paulo Roberto Andrade De Freitas",
              "Rachel Medeiros Germano",
              "Rafael Silva Paes Pires Galvão",
              "Raquel Batista De Ataide Fagundes",
              "Rebecca Monte Nunes Bezerra",
              "Relva Gardene Rolim Dos Santos",
              "Ricardo José Da Costa Lima",
              "Ricardo Manoel Da Cruz Formiga",
              "Rinaldo Reis Lima",
              "Roberta De Fátima Alves Pinheiro",
              "Rodrigo Martins Da Câmara",
              "Rodrigo Pessoa De Morais",
              "Roger De Melo Rodrigues",
              "Rosane Cristina Pessoa Moreno",
              "Rossana Campos Cavalcanti Pinheiro",
              "Rozana Cristina Fagundes De Lima",
              "Sandra Angelica Pereira Santiago",
              "Sasha Alves Do Amaral",
              "Sérgio Gouveia De Macêdo",
              "Sérgio Luiz De Sena",
              "Sidharta John Batista Da Silva",
              "Silvio Ricardo Goncalves De Andrade Brito",
              "Sílvio Roberto Souza Lima",
              "Suely Magna De Carvalho Nobre Felipe",
              "Tatiana Kalina Macêdo Chaves",
              "Tatianne Sabrine De Lima Barbosa Brito",
              "Thatiana Kaline Fernandes",
              "Thiago Salles Assunção",
              "Thibério César Do Nascimento Fernandes",
              "Tiffany Mourão Cavalari De Lima",
              "Uliana Lemos De Paiva",
              "Vicente Elísio De Oliveira Neto",
              "Victor Hugo De Freitas Leite",
              "Vinícius Lins Leão Lima",
              "Vítor Emanuel De Medeiros Azevedo",
              "Wendell Beetoven Ribeiro",
              "Wendell Beetoven Ribeiro Agra",
              "Wilkson Vieira Barbosa Silva",
              "Wilmar Carlos De Paiva Leite Filho",
              "Yvellise Nery Da Costa",
              "Yves Porfirio Castro De Albuquerque"]

dados_fixos = {
    'Item': ['Resolutividade (Produtividade e impacto social)',
             'Resolutividade (Produtividade e impacto social)',
             'Resolutividade (Produtividade e impacto social)',
             'Resolutividade (Produtividade e impacto social)',

             'Presteza',
             'Presteza',
             'Presteza',
             'Pronto Antedimento',
             'Eficiência',
             'Organização e Desempenho das Funções',
             'Qualidade Técnica',
             'Segurança',
             'Participação em Mutirões e/ou Sessões do Júri',
             'Cursos de Formação Continuada',
             'Cursos Oficiais Diversos dos de Formação Continuada e Cursos Reconhecidos de Aperfeiçoamento',
             'Cursos Oficiais Diversos dos de Formação Continuada e Cursos Reconhecidos de Aperfeiçoamento',
             'Aprimoramento - Doutorado',
             'Aprimoramento - Mestrado ',
             'Aprimoramento - Especialização',
             'Publicações Acadêmicas',
             'Conduta Profissional e Privada',
             ],

    'Informações': [
        'Último Relatório de Correição',
        'Comparativo atualizado',
        'Bizagi Ficha 15',
        'Drive CGMP-Resultados',

        'Fichas 15 e 16 do Bizagi',
        'Último Relatório de Correição',
        'Certidão da DCOG',

        'Certidão da DCOG',
        'Ficha 3 EXTRATO_MERECIMENTO BIZAGI',
        'Ficha 3 EXTRATO_MERECIMENTO BIZAGI',
        'Ficha 3 EXTRATO_MERECIMENTO BIZAGI',
        'Ficha 3 EXTRATO_MERECIMENTO BIZAGI',
        'Ficha 6 EXTRATO_MERECIMENTO BIZAGI',
        'Ficha 11 EXTRATO_MERECIMENTO BIZAGI',
        'Ficha 12 EXTRATO_MERECIMENTO BIZAGI',
        'Ficha 13 EXTRATO_MERECIMENTO BIZAGI',

        'Ficha 10 EXTRATO_MERECIMENTO BIZAGI',
        'Ficha 10 EXTRATO_MERECIMENTO BIZAGI',
        'Ficha 10 EXTRATO_MERECIMENTO BIZAGI',
        'Ficha 8 EXTRATO_MERECIMENTO BIZAGI',
        'EXTRATO_MERECIMENTO BIZAGI',
    ],

    'Localização das Informações': [
        '{{Último Relatório de Correição}}',
        '{{Comparativo atualizado}}',
        '{{Bizagi - Ficha 15}}',
        '------',
        '{{Bizagi - Ficha 15 e 16}}',
        '{{Último Relatório de Correição}}',
        '{{Certidão da Diretoria da Corregedoria-Geral}}',
        '{{Certidão da Diretoria da Corregedoria-Geral}}',
        '{{Bizagi - Ficha 3}}',
        '{{Bizagi - Ficha 3}}',
        '{{Bizagi - Ficha 3}}',
        '{{Bizagi - Ficha 3}}',
        '{{Bizagi - Ficha 6}}',
        '{{Bizagi - Ficha 11}}',
        '{{Bizagi - Ficha 12}}',
        '{{Bizagi - Ficha 13}}',
        '{{Bizagi - Ficha 10}}',
        '{{Bizagi - Ficha 10}}',
        '{{Bizagi - Ficha 10}}',
        '{{Bizagi - Ficha 8}}',
        '{{Bizagi - Integral}}',
    ],



}
